// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: relay.proto

package membership

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MembershipService_Register_FullMethodName        = "/relay.MembershipService/Register"
	MembershipService_Deregister_FullMethodName      = "/relay.MembershipService/Deregister"
	MembershipService_GetAliveMembers_FullMethodName = "/relay.MembershipService/GetAliveMembers"
	MembershipService_WatchMembership_FullMethodName = "/relay.MembershipService/WatchMembership"
	MembershipService_Put_FullMethodName             = "/relay.MembershipService/Put"
	MembershipService_Get_FullMethodName             = "/relay.MembershipService/Get"
	MembershipService_GetByPrefix_FullMethodName     = "/relay.MembershipService/GetByPrefix"
	MembershipService_HoldLeadership_FullMethodName  = "/relay.MembershipService/HoldLeadership"
	MembershipService_HoldLease_FullMethodName       = "/relay.MembershipService/HoldLease"
	MembershipService_PutWithLease_FullMethodName    = "/relay.MembershipService/PutWithLease"
)

// MembershipServiceClient is the client API for MembershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MembershipServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Deregister(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*Empty, error)
	GetAliveMembers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MemberList, error)
	WatchMembership(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MemberEvent], error)
	Put(ctx context.Context, in *KVPair, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*ValueResponse, error)
	GetByPrefix(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*KVList, error)
	// Hold open while this node is the elected leader; server resigns when stream closes.
	HoldLeadership(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaderStatus], error)
	// Hold a lease alive while this stream is open. Server creates an etcd session
	// with the requested TTL, yields the lease id once, and keeps it alive until
	// the stream closes (graceful client close or transport failure). When the
	// stream ends the session is revoked and every key attached to the lease is
	// auto-deleted by etcd within the TTL window.
	HoldLease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseStatus], error)
	// Write a key bound to the given lease id; the key is deleted automatically
	// when the lease expires or is revoked.
	PutWithLease(ctx context.Context, in *LeaseKVPair, opts ...grpc.CallOption) (*Empty, error)
}

type membershipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipServiceClient(cc grpc.ClientConnInterface) MembershipServiceClient {
	return &membershipServiceClient{cc}
}

func (c *membershipServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, MembershipService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) Deregister(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MembershipService_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetAliveMembers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MemberList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberList)
	err := c.cc.Invoke(ctx, MembershipService_GetAliveMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) WatchMembership(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MemberEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MembershipService_ServiceDesc.Streams[0], MembershipService_WatchMembership_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, MemberEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MembershipService_WatchMembershipClient = grpc.ServerStreamingClient[MemberEvent]

func (c *membershipServiceClient) Put(ctx context.Context, in *KVPair, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MembershipService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) Get(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*ValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValueResponse)
	err := c.cc.Invoke(ctx, MembershipService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetByPrefix(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*KVList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVList)
	err := c.cc.Invoke(ctx, MembershipService_GetByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) HoldLeadership(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaderStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MembershipService_ServiceDesc.Streams[1], MembershipService_HoldLeadership_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, LeaderStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MembershipService_HoldLeadershipClient = grpc.ServerStreamingClient[LeaderStatus]

func (c *membershipServiceClient) HoldLease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MembershipService_ServiceDesc.Streams[2], MembershipService_HoldLease_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LeaseRequest, LeaseStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MembershipService_HoldLeaseClient = grpc.ServerStreamingClient[LeaseStatus]

func (c *membershipServiceClient) PutWithLease(ctx context.Context, in *LeaseKVPair, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MembershipService_PutWithLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServiceServer is the server API for MembershipService service.
// All implementations must embed UnimplementedMembershipServiceServer
// for forward compatibility.
type MembershipServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Deregister(context.Context, *NodeIdRequest) (*Empty, error)
	GetAliveMembers(context.Context, *Empty) (*MemberList, error)
	WatchMembership(*Empty, grpc.ServerStreamingServer[MemberEvent]) error
	Put(context.Context, *KVPair) (*Empty, error)
	Get(context.Context, *KeyRequest) (*ValueResponse, error)
	GetByPrefix(context.Context, *KeyRequest) (*KVList, error)
	// Hold open while this node is the elected leader; server resigns when stream closes.
	HoldLeadership(*Empty, grpc.ServerStreamingServer[LeaderStatus]) error
	// Hold a lease alive while this stream is open. Server creates an etcd session
	// with the requested TTL, yields the lease id once, and keeps it alive until
	// the stream closes (graceful client close or transport failure). When the
	// stream ends the session is revoked and every key attached to the lease is
	// auto-deleted by etcd within the TTL window.
	HoldLease(*LeaseRequest, grpc.ServerStreamingServer[LeaseStatus]) error
	// Write a key bound to the given lease id; the key is deleted automatically
	// when the lease expires or is revoked.
	PutWithLease(context.Context, *LeaseKVPair) (*Empty, error)
	mustEmbedUnimplementedMembershipServiceServer()
}

// UnimplementedMembershipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipServiceServer struct{}

func (UnimplementedMembershipServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedMembershipServiceServer) Deregister(context.Context, *NodeIdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedMembershipServiceServer) GetAliveMembers(context.Context, *Empty) (*MemberList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAliveMembers not implemented")
}
func (UnimplementedMembershipServiceServer) WatchMembership(*Empty, grpc.ServerStreamingServer[MemberEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchMembership not implemented")
}
func (UnimplementedMembershipServiceServer) Put(context.Context, *KVPair) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedMembershipServiceServer) Get(context.Context, *KeyRequest) (*ValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMembershipServiceServer) GetByPrefix(context.Context, *KeyRequest) (*KVList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByPrefix not implemented")
}
func (UnimplementedMembershipServiceServer) HoldLeadership(*Empty, grpc.ServerStreamingServer[LeaderStatus]) error {
	return status.Error(codes.Unimplemented, "method HoldLeadership not implemented")
}
func (UnimplementedMembershipServiceServer) HoldLease(*LeaseRequest, grpc.ServerStreamingServer[LeaseStatus]) error {
	return status.Error(codes.Unimplemented, "method HoldLease not implemented")
}
func (UnimplementedMembershipServiceServer) PutWithLease(context.Context, *LeaseKVPair) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PutWithLease not implemented")
}
func (UnimplementedMembershipServiceServer) mustEmbedUnimplementedMembershipServiceServer() {}
func (UnimplementedMembershipServiceServer) testEmbeddedByValue()                           {}

// UnsafeMembershipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipServiceServer will
// result in compilation errors.
type UnsafeMembershipServiceServer interface {
	mustEmbedUnimplementedMembershipServiceServer()
}

func RegisterMembershipServiceServer(s grpc.ServiceRegistrar, srv MembershipServiceServer) {
	// If the following call panics, it indicates UnimplementedMembershipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MembershipService_ServiceDesc, srv)
}

func _MembershipService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).Deregister(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetAliveMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetAliveMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetAliveMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetAliveMembers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_WatchMembership_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MembershipServiceServer).WatchMembership(m, &grpc.GenericServerStream[Empty, MemberEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MembershipService_WatchMembershipServer = grpc.ServerStreamingServer[MemberEvent]

func _MembershipService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).Put(ctx, req.(*KVPair))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).Get(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetByPrefix(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_HoldLeadership_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MembershipServiceServer).HoldLeadership(m, &grpc.GenericServerStream[Empty, LeaderStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MembershipService_HoldLeadershipServer = grpc.ServerStreamingServer[LeaderStatus]

func _MembershipService_HoldLease_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LeaseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MembershipServiceServer).HoldLease(m, &grpc.GenericServerStream[LeaseRequest, LeaseStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MembershipService_HoldLeaseServer = grpc.ServerStreamingServer[LeaseStatus]

func _MembershipService_PutWithLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseKVPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).PutWithLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_PutWithLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).PutWithLease(ctx, req.(*LeaseKVPair))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipService_ServiceDesc is the grpc.ServiceDesc for MembershipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relay.MembershipService",
	HandlerType: (*MembershipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _MembershipService_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _MembershipService_Deregister_Handler,
		},
		{
			MethodName: "GetAliveMembers",
			Handler:    _MembershipService_GetAliveMembers_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _MembershipService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MembershipService_Get_Handler,
		},
		{
			MethodName: "GetByPrefix",
			Handler:    _MembershipService_GetByPrefix_Handler,
		},
		{
			MethodName: "PutWithLease",
			Handler:    _MembershipService_PutWithLease_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMembership",
			Handler:       _MembershipService_WatchMembership_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HoldLeadership",
			Handler:       _MembershipService_HoldLeadership_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HoldLease",
			Handler:       _MembershipService_HoldLease_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "relay.proto",
}
