// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: relay.proto

package membership

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberEvent_Type int32

const (
	MemberEvent_JOINED MemberEvent_Type = 0
	MemberEvent_LEFT   MemberEvent_Type = 1
)

// Enum value maps for MemberEvent_Type.
var (
	MemberEvent_Type_name = map[int32]string{
		0: "JOINED",
		1: "LEFT",
	}
	MemberEvent_Type_value = map[string]int32{
		"JOINED": 0,
		"LEFT":   1,
	}
)

func (x MemberEvent_Type) Enum() *MemberEvent_Type {
	p := new(MemberEvent_Type)
	*p = x
	return p
}

func (x MemberEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[0].Descriptor()
}

func (MemberEvent_Type) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[0]
}

func (x MemberEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberEvent_Type.Descriptor instead.
func (MemberEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,2,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NodeIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdRequest) Reset() {
	*x = NodeIdRequest{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdRequest) ProtoMessage() {}

func (x *NodeIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdRequest.ProtoReflect.Descriptor instead.
func (*NodeIdRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *NodeIdRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,2,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{4}
}

func (x *MemberList) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type MemberEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MemberEvent_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=relay.MemberEvent_Type" json:"type,omitempty"`
	Node          *Node                  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberEvent) Reset() {
	*x = MemberEvent{}
	mi := &file_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberEvent) ProtoMessage() {}

func (x *MemberEvent) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberEvent.ProtoReflect.Descriptor instead.
func (*MemberEvent) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5}
}

func (x *MemberEvent) GetType() MemberEvent_Type {
	if x != nil {
		return x.Type
	}
	return MemberEvent_JOINED
}

func (x *MemberEvent) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type KVPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	mi := &file_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{6}
}

func (x *KVPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRequest) Reset() {
	*x = KeyRequest{}
	mi := &file_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRequest) ProtoMessage() {}

func (x *KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRequest.ProtoReflect.Descriptor instead.
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{7}
}

func (x *KeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueResponse) Reset() {
	*x = ValueResponse{}
	mi := &file_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueResponse) ProtoMessage() {}

func (x *ValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueResponse.ProtoReflect.Descriptor instead.
func (*ValueResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{8}
}

func (x *ValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ValueResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type KVList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KVPair              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVList) Reset() {
	*x = KVList{}
	mi := &file_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVList) ProtoMessage() {}

func (x *KVList) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVList.ProtoReflect.Descriptor instead.
func (*KVList) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{9}
}

func (x *KVList) GetItems() []*KVPair {
	if x != nil {
		return x.Items
	}
	return nil
}

type LeaderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLeader      bool                   `protobuf:"varint,1,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderStatus) Reset() {
	*x = LeaderStatus{}
	mi := &file_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderStatus) ProtoMessage() {}

func (x *LeaderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderStatus.ProtoReflect.Descriptor instead.
func (*LeaderStatus) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{10}
}

func (x *LeaderStatus) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *LeaderStatus) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type LeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested TTL in seconds. Server clamps to a sensible range (e.g. >= 5).
	TtlSeconds    int64 `protobuf:"varint,1,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{11}
}

func (x *LeaseRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type LeaseStatus struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	LeaseId int64                  `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// Stays true for the lifetime of the stream. Provided so the client knows
	// the lease was successfully granted before the first PutWithLease.
	Alive         bool `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseStatus) Reset() {
	*x = LeaseStatus{}
	mi := &file_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseStatus) ProtoMessage() {}

func (x *LeaseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseStatus.ProtoReflect.Descriptor instead.
func (*LeaseStatus) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{12}
}

func (x *LeaseStatus) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *LeaseStatus) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type LeaseKVPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LeaseId       int64                  `protobuf:"varint,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseKVPair) Reset() {
	*x = LeaseKVPair{}
	mi := &file_relay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseKVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseKVPair) ProtoMessage() {}

func (x *LeaseKVPair) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseKVPair.ProtoReflect.Descriptor instead.
func (*LeaseKVPair) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{13}
}

func (x *LeaseKVPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LeaseKVPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LeaseKVPair) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_relay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{14}
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\x05relay\"O\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rmetadata_json\x18\x02 \x01(\tR\fmetadataJson\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\rNodeIdRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\";\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmetadata_json\x18\x02 \x01(\tR\fmetadataJson\"/\n" +
	"\n" +
	"MemberList\x12!\n" +
	"\x05nodes\x18\x01 \x03(\v2\v.relay.NodeR\x05nodes\"y\n" +
	"\vMemberEvent\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.relay.MemberEvent.TypeR\x04type\x12\x1f\n" +
	"\x04node\x18\x02 \x01(\v2\v.relay.NodeR\x04node\"\x1c\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06JOINED\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\"0\n" +
	"\x06KVPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1e\n" +
	"\n" +
	"KeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\rValueResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"-\n" +
	"\x06KVList\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.relay.KVPairR\x05items\"H\n" +
	"\fLeaderStatus\x12\x1b\n" +
	"\tis_leader\x18\x01 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\"/\n" +
	"\fLeaseRequest\x12\x1f\n" +
	"\vttl_seconds\x18\x01 \x01(\x03R\n" +
	"ttlSeconds\">\n" +
	"\vLeaseStatus\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x03R\aleaseId\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\bR\x05alive\"P\n" +
	"\vLeaseKVPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\x03R\aleaseId\"\a\n" +
	"\x05Empty2\x93\x04\n" +
	"\x11MembershipService\x12;\n" +
	"\bRegister\x12\x16.relay.RegisterRequest\x1a\x17.relay.RegisterResponse\x120\n" +
	"\n" +
	"Deregister\x12\x14.relay.NodeIdRequest\x1a\f.relay.Empty\x122\n" +
	"\x0fGetAliveMembers\x12\f.relay.Empty\x1a\x11.relay.MemberList\x125\n" +
	"\x0fWatchMembership\x12\f.relay.Empty\x1a\x12.relay.MemberEvent0\x01\x12\"\n" +
	"\x03Put\x12\r.relay.KVPair\x1a\f.relay.Empty\x12.\n" +
	"\x03Get\x12\x11.relay.KeyRequest\x1a\x14.relay.ValueResponse\x12/\n" +
	"\vGetByPrefix\x12\x11.relay.KeyRequest\x1a\r.relay.KVList\x125\n" +
	"\x0eHoldLeadership\x12\f.relay.Empty\x1a\x13.relay.LeaderStatus0\x01\x126\n" +
	"\tHoldLease\x12\x13.relay.LeaseRequest\x1a\x12.relay.LeaseStatus0\x01\x120\n" +
	"\fPutWithLease\x12\x12.relay.LeaseKVPair\x1a\f.relay.EmptyB\"Z relay/membership-etcd/membershipb\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_relay_proto_goTypes = []any{
	(MemberEvent_Type)(0),    // 0: relay.MemberEvent.Type
	(*RegisterRequest)(nil),  // 1: relay.RegisterRequest
	(*RegisterResponse)(nil), // 2: relay.RegisterResponse
	(*NodeIdRequest)(nil),    // 3: relay.NodeIdRequest
	(*Node)(nil),             // 4: relay.Node
	(*MemberList)(nil),       // 5: relay.MemberList
	(*MemberEvent)(nil),      // 6: relay.MemberEvent
	(*KVPair)(nil),           // 7: relay.KVPair
	(*KeyRequest)(nil),       // 8: relay.KeyRequest
	(*ValueResponse)(nil),    // 9: relay.ValueResponse
	(*KVList)(nil),           // 10: relay.KVList
	(*LeaderStatus)(nil),     // 11: relay.LeaderStatus
	(*LeaseRequest)(nil),     // 12: relay.LeaseRequest
	(*LeaseStatus)(nil),      // 13: relay.LeaseStatus
	(*LeaseKVPair)(nil),      // 14: relay.LeaseKVPair
	(*Empty)(nil),            // 15: relay.Empty
}
var file_relay_proto_depIdxs = []int32{
	4,  // 0: relay.MemberList.nodes:type_name -> relay.Node
	0,  // 1: relay.MemberEvent.type:type_name -> relay.MemberEvent.Type
	4,  // 2: relay.MemberEvent.node:type_name -> relay.Node
	7,  // 3: relay.KVList.items:type_name -> relay.KVPair
	1,  // 4: relay.MembershipService.Register:input_type -> relay.RegisterRequest
	3,  // 5: relay.MembershipService.Deregister:input_type -> relay.NodeIdRequest
	15, // 6: relay.MembershipService.GetAliveMembers:input_type -> relay.Empty
	15, // 7: relay.MembershipService.WatchMembership:input_type -> relay.Empty
	7,  // 8: relay.MembershipService.Put:input_type -> relay.KVPair
	8,  // 9: relay.MembershipService.Get:input_type -> relay.KeyRequest
	8,  // 10: relay.MembershipService.GetByPrefix:input_type -> relay.KeyRequest
	15, // 11: relay.MembershipService.HoldLeadership:input_type -> relay.Empty
	12, // 12: relay.MembershipService.HoldLease:input_type -> relay.LeaseRequest
	14, // 13: relay.MembershipService.PutWithLease:input_type -> relay.LeaseKVPair
	2,  // 14: relay.MembershipService.Register:output_type -> relay.RegisterResponse
	15, // 15: relay.MembershipService.Deregister:output_type -> relay.Empty
	5,  // 16: relay.MembershipService.GetAliveMembers:output_type -> relay.MemberList
	6,  // 17: relay.MembershipService.WatchMembership:output_type -> relay.MemberEvent
	15, // 18: relay.MembershipService.Put:output_type -> relay.Empty
	9,  // 19: relay.MembershipService.Get:output_type -> relay.ValueResponse
	10, // 20: relay.MembershipService.GetByPrefix:output_type -> relay.KVList
	11, // 21: relay.MembershipService.HoldLeadership:output_type -> relay.LeaderStatus
	13, // 22: relay.MembershipService.HoldLease:output_type -> relay.LeaseStatus
	15, // 23: relay.MembershipService.PutWithLease:output_type -> relay.Empty
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		EnumInfos:         file_relay_proto_enumTypes,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
