import asyncio
import json
from collections.abc import AsyncIterator
from typing import Callable

import grpc
import grpc.aio
from loguru import logger

from .base import MembershipLayer, Node

# Generated by `make proto` — run that before importing this module.
try:
    from . import relay_pb2, relay_pb2_grpc
except ImportError as e:
    raise ImportError("gRPC stubs not found. Run `make proto` first.") from e


class EtcdMembership(MembershipLayer):
    """MembershipLayer backed by the etcd-go gRPC middleware."""

    def __init__(self, host: str = "localhost", port: int = 50051) -> None:
        """Open an async gRPC channel to the membership-etcd server."""
        self._channel = grpc.aio.insecure_channel(f"{host}:{port}")
        self._stub = relay_pb2_grpc.MembershipServiceStub(self._channel)
        self._leaseId: int | None = None
        self._leaseStream: (
            grpc.aio.UnaryStreamCall[relay_pb2.LeaseRequest, relay_pb2.LeaseStatus] | None
        ) = None
        self._leaseTask: asyncio.Task[None] | None = None
        self._leaseReady: asyncio.Event = asyncio.Event()
        logger.info("EtcdMembership channel opened | target={}:{}", host, port)

    async def register(self, nodeId: str, metadata: dict) -> None:
        """Register this node in etcd under /relay/nodes/{nodeId}."""
        await self._stub.Register(
            relay_pb2.RegisterRequest(
                node_id=nodeId,
                metadata_json=json.dumps(metadata),
            )
        )
        logger.debug("Node registered | nodeId={}", nodeId)

    async def deregister(self, nodeId: str) -> None:
        """Delete this node's key from etcd."""
        await self._stub.Deregister(relay_pb2.NodeIdRequest(node_id=nodeId))
        logger.debug("Node deregistered | nodeId={}", nodeId)

    async def getAliveMembers(self) -> list[Node]:
        """Fetch all /relay/nodes/ keys from etcd and deserialize them."""
        resp = await self._stub.GetAliveMembers(relay_pb2.Empty())
        members = [Node(id=n.id, metadata=json.loads(n.metadata_json)) for n in resp.nodes]
        logger.debug("Fetched alive members | count={}", len(members))
        return members

    def watchMembership(self, callback: Callable[[str, Node], None]) -> None:
        """Start a background asyncio task streaming membership events from etcd."""
        logger.info("Starting membership watch stream")
        asyncio.create_task(self._streamLoop(callback))

    async def _streamLoop(self, callback: Callable[[str, Node], None]) -> None:
        """Consume the WatchMembership stream and invoke callback on each event."""
        try:
            async for event in self._stub.WatchMembership(relay_pb2.Empty()):
                eventType = "JOINED" if event.type == relay_pb2.MemberEvent.JOINED else "LEFT"
                node = Node(
                    id=event.node.id,
                    metadata=json.loads(event.node.metadata_json),
                )
                logger.info("Membership event | type={} nodeId={}", eventType, node.id)
                callback(eventType, node)
        except Exception:
            logger.exception("Membership watch stream terminated unexpectedly")

    async def holdLeadership(self) -> AsyncIterator[bool]:  # type: ignore[override]
        """Campaign for leadership; yield True when elected. Returns when stream ends."""
        async for status in self._stub.HoldLeadership(relay_pb2.Empty()):
            logger.debug(
                "Leadership status | isLeader={} leaderId={}", status.is_leader, status.leader_id
            )
            yield status.is_leader

    async def put(self, key: str, value: str) -> None:
        """Write a key-value pair to etcd."""
        await self._stub.Put(relay_pb2.KVPair(key=key, value=value))
        logger.debug("etcd put | key={}", key)

    async def get(self, key: str) -> str | None:
        """Read a value from etcd; returns None if the key does not exist."""
        resp = await self._stub.Get(relay_pb2.KeyRequest(key=key))
        logger.debug("etcd get | key={} found={}", key, resp.found)
        return resp.value if resp.found else None

    async def getByPrefix(self, prefix: str) -> dict[str, str]:
        """Return all key-value pairs from etcd whose keys start with the given prefix."""
        resp = await self._stub.GetByPrefix(relay_pb2.KeyRequest(key=prefix))
        result = {item.key: item.value for item in resp.items}
        logger.debug("etcd getByPrefix | prefix={} count={}", prefix, len(result))
        return result

    async def holdLease(self, ttlSeconds: int = 10) -> int:
        """Grant a session-backed lease via HoldLease and keep the stream alive."""
        if self._leaseTask is not None:
            await self._leaseReady.wait()
            assert self._leaseId is not None
            return self._leaseId
        self._leaseTask = asyncio.create_task(self._runLeaseStream(ttlSeconds))
        await self._leaseReady.wait()
        if self._leaseId is None:
            raise RuntimeError("HoldLease did not produce a lease id")
        return self._leaseId

    async def _runLeaseStream(self, ttlSeconds: int) -> None:
        """Hold the HoldLease server-stream open until the channel closes."""
        try:
            self._leaseStream = self._stub.HoldLease(relay_pb2.LeaseRequest(ttl_seconds=ttlSeconds))
            async for status in self._leaseStream:
                if status.lease_id and self._leaseId is None:
                    self._leaseId = int(status.lease_id)
                    logger.info("HoldLease granted | leaseId={}", self._leaseId)
                    self._leaseReady.set()
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("HoldLease stream terminated")
        finally:
            # If the stream died before yielding, unblock the waiter so the
            # caller can see the failure instead of hanging forever.
            self._leaseReady.set()

    async def putWithLease(self, key: str, value: str) -> None:
        """Write a key bound to the currently-held lease."""
        if self._leaseId is None:
            raise RuntimeError("putWithLease called before holdLease")
        await self._stub.PutWithLease(
            relay_pb2.LeaseKVPair(key=key, value=value, lease_id=self._leaseId)
        )
        logger.debug("etcd putWithLease | key={} leaseId={}", key, self._leaseId)

    async def close(self) -> None:
        """Close the gRPC channel, revoking any held lease via stream cancellation."""
        if self._leaseTask is not None:
            self._leaseTask.cancel()
            try:
                await self._leaseTask
            except (asyncio.CancelledError, Exception):
                pass
            self._leaseTask = None
            self._leaseId = None
        await self._channel.close()
        logger.info("EtcdMembership gRPC channel closed")
